version: '2.1'
services:
  app:
    restart: always
    build:
      context: .
      args:
        dev: "true"
    command: "npm start"
    ports:
     - "3000:3000"
    env_file:
     - .env
    volumes:
     - .:/home/node
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mongo
    restart: always
    ports:
     - 27017
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.stats().ok' | mongo 127.0.0.1/test --quiet"]
      interval: 2s
      timeout: 10s
      retries: 3
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb
